feat: add support for .mjs file output
floydspace/serverless-esbuild pull request #333
Opened 2022-07-15 10:16 UTC by codingnuclei

Hey.

This PR adds outputting `.mjs` files if the build option `platform=neutral`.

Currently we can use `platform=neutral` to output the bundle as esm. The bundle extension however remains `.js`. This is fine when it is accompanied by a `package.json` which has `"type": "module"` set.

However, the `package.json' is explicitly not included in the final zip.

https://github.com/floydspace/serverless-esbuild/blob/master/src/pack.ts#L38

This means that lambdas run the code as CommonJs.

Changing the file type seems a more explicit option (rather than package the `package.json`)

## Considerations:
- `platform=neutral` now outputs `.mjs` files

## Notes on testing
- How typing is currently set up, it is hard to change `buildOptions` in tests.  I have therefore casted when added to the overrides.  Keeping the variable typed should ensure the type safety.

First PR to serverless-esbuild so let me know if you require anything else.

Partially closes #315 (`package.json` is no longer required)

2022-07-17 22:23 UTC, codingnuclei commented
PR changed to be more configurable

2022-07-18 07:45 UTC, floydspace commented
Hi @codingnuclei , thank you for the careful PR. I think it's a necessary addition.
I'm happy to merge it, but please consider my comments about serverless error

2022-07-18 08:42 UTC, codingnuclei commented
> Hi @codingnuclei , thank you for the careful PR. I think it's a necessary addition. I'm happy to merge it, but please consider my comments about serverless error

This might be me being silly - but I am not seeing any comments?

2022-07-18 08:47 UTC, floydspace requested changes

2022-07-18 09:22 UTC, floydspace commented on src/bundle.ts
> +    throw new Error('ERROR: platform "neutral" should not output a file with extension ".cjs".');
Yes unfortunately types are not perfect, and I see the newest definitely types does not have it either,
so you could just assume it or extend types by defining custom `d.ts` for the module in the root `/typings` folder if you'd like, but it's out of the scope of this PR

2022-07-18 11:12 UTC, codingnuclei commented on src/bundle.ts
> +    throw new Error('ERROR: platform "neutral" should not output a file with extension ".cjs".');
Assumed typings for this PR

2022-07-18 11:16 UTC, codingnuclei commented
@floydspace updated with your comments resolved :)

2022-07-18 11:49 UTC, floydspace approved these changes
@codingnuclei thank you, approved.

2022-07-18 11:49 UTC, merged